### ISSUE TITLE
Seems no longer functional since recent minor update

### ISSUE THREAD

**Issue by wiyrdhamster** [azzu0/Melon#4]
After some update done recently, this melonloader is no longer functional in current 3.7 version. 
It will fire 31-4302 error, though it is not permanent (not trying to use melon will fix it. but melon is de facto blocked)

Meanwhile, camera range change from QoL by portra is broken. Cannot complain about this since that is someone elses' work, but I wonder if I can have access to portra's repository if they still have any. I cannot find them on search engines anymore.

**Comment by azzu0** [comment]
The 31-4302 error happens when the official servers enforce an integrity check. To get around this you need a checksum bypass which hasn't been updated.
The mods have been fixed in 3.8. The original QoL repo is here https://github.com/portra400nc/QoL
